version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root